### PR TITLE
Add support for Azure, OpenAI, Palm, Anthropic, Cohere, Replicate Models - using litellm 

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for models from all the above mentioned providers using https://github.com/BerriAI/litellm/

Here's a sample of how it's used:

```
from litellm import completion, acompletion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# async openai
response = acompletion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@basicthinker @yangbobo2021 can you take a look at this PR? 
If the initial commit looks good happy to add to the readme / testing too😊

**Comment by basicthinker** [comment]
@ishaan-jaff great work, thanks! Before I look more into your project, could you quickly explain how we can control which model to use and their parameters? Any unified or separate config? Do you support OpenAI functions? How are the function semantics realized in other models such as Claude 2?

**Comment by ishaan-jaff** [comment]
> could you quickly explain how we can control which model to use and their parameters?

You can control the model, using the `model` param, supported models are listed here https://litellm.readthedocs.io/en/latest/supported/ 
As for the input params - they're exactly the same as chatGPT. For Non OpenAI providers litellm manages the translation of input/output. 

> Any unified or separate config? 
Can you elaborate on this ? Is there something we can add to litellm for you here - to make it easier for you ? 

> Do you support OpenAI functions?

Yes

> How are the function semantics realized in other models such as Claude 2?

As of now we don't support Claude 2 function calling. Any suggestions on if litellm should handle translating function calling ?

**Comment by basicthinker** [comment]
> > Any unified or separate config?
> 
> Can you elaborate on this ? Is there something we can add to litellm for you here - to make it easier for you ?
> 

@ishaan-jaff Thanks for the above clarification. This question is about parameters of a LLM. Say, temperature, streaming, etc. for OpenAI. Now we use a config file to store default parameters so that you don't need to specify them on each call. How do you manage the parameters for different LLMs? Can I store them also in a config file?

**Comment by ishaan-jaff** [comment]
@basicthinker this is addressed, you can now use 
```
litellm.config_path = "../config.json"
response = litellm.config_completion(messages=messages)
```

let me know where we should add `config_completion()`

**Pull request merged**
